# Deliverable 3. Create a Travel Itinerary Map.
----
1. Import the vacation CSV file. 
2. From the map above with pick 4 cities that are in close proximity (on the same continent) that the customer would travel to and create a directions layer map.
3. For the "travel_mode" use either "DRIVING", "BICYCLING", or "WALKING".
4. Take a screenshot of the route and save it. 
5. Then create a marker layer for the four cities. Each city will should have a pop-up marker that contains
    - The hotel name
    - The city
    - The country
    - The current weather description and the maximum temperature
---

## Make sure the initial dependencies and the Google API key are imported.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

In [2]:
# Configure gmaps
gmaps.configure(api_key=g_key)

## From your `Vacation_Search` folder from Deliverable 2, import the `WeatherPy_vacation.csv` file as a DataFrame named `vacation_df`

In [3]:
# Read the WeatherPy_vacation.csv into a DataFrame
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv", index_col= None)
#vacation_df = vacation_df["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description",
#"Hotel Name"]
vacation_df = vacation_df[["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description",
"Hotel Name"]]

# Display sample data
vacation_df
# YOUR CODE HERE

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
0,Kapaa,US,22.0752,-159.3190,84.18,68,100,10.36,overcast clouds,Sheraton Kauai Coconut Beach Resort
1,Hilo,US,19.7297,-155.0900,83.28,81,100,9.22,overcast clouds,Hilo Hawaiian Hotel
2,Bengkulu,ID,-3.8004,102.2655,81.81,70,83,1.23,broken clouds,Grage Hotel Bengkulu
3,Rikitea,PF,-23.1203,-134.9692,71.13,69,5,18.23,clear sky,People ThankYou
4,Vaini,TO,-21.2000,-175.2000,77.16,83,75,12.66,broken clouds,Keleti Beach Resort
...,...,...,...,...,...,...,...,...,...,...
277,Sao Jose Da Coroa Grande,BR,-8.8978,-35.1478,76.14,87,55,8.81,broken clouds,Crôa Mares Hotel
278,Affery,CI,6.3150,-3.9603,71.38,100,92,1.90,overcast clouds,Hôtel l'auberge grenobloise
279,Marabba,SD,12.3500,32.1833,75.51,79,98,11.63,overcast clouds,NaN
280,Biak,ID,-0.9131,122.8766,82.87,72,90,3.27,overcast clouds,Penginapan Kim
281,Aswan,EG,24.0934,32.9070,74.05,39,0,13.67,clear sky,Nuba Nile

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [4]:
# In case of an empty DataFrame, load the sample data provided
clean_hotel_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation-backup.csv")
clean_hotel_df = clean_hotel_df[["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description",
"Hotel Name"]]
clean_hotel_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
0,Kapaa,US,22.0752,-159.3190,84.18,68,100,10.36,overcast clouds,Sheraton Kauai Coconut Beach Resort
1,Hilo,US,19.7297,-155.0900,83.28,81,100,9.22,overcast clouds,Hilo Hawaiian Hotel
2,Bengkulu,ID,-3.8004,102.2655,81.81,70,83,1.23,broken clouds,Grage Hotel Bengkulu
3,Rikitea,PF,-23.1203,-134.9692,71.13,69,5,18.23,clear sky,People ThankYou
4,Vaini,TO,-21.2000,-175.2000,77.16,83,75,12.66,broken clouds,Keleti Beach Resort
5,Salalah,OM,17.0151,54.0924,77.09,73,75,5.75,broken clouds,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
6,Butaritari,KI,3.0707,172.7902,82.26,73,13,15.10,few clouds,Isles Sunset Lodge
7,Sinnamary,GF,5.3833,-52.9500,79.86,87,89,11.99,overcast clouds,ALETHEIA Appartement Sinnamary
8,Porto Novo,BJ,6.4965,2.6036,78.62,94,98,2.51,light rain,Tour Eiffel Hotel Benin
9,Portland,US,45.5234,-122.6762,78.84,54,20,6.91,smoke,Embassy Suites by Hilton Portland Downtown

## In this step, you will set-up the pop-up markers. Review the code to create a marker layer map of the vacation search results. This code is the same as in Deliverable 2.

In [5]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [6]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

## From the vacation search map, *choose four cities* that a customer might want to visit. They should be close together and in the same country.

In [7]:
# Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df["City"] == "Portland"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Portland"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "San Jose"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Morro Bay"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Saint George"]
vacation_start

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
9,Portland,US,45.5234,-122.6762,78.84,54,20,6.91,smoke,Embassy Suites by Hilton Portland Downtown

## Use the `to_numpy()` function and list indexing to write code to retrieve the latitude-longitude pairs as tuples from each city DataFrame.

In [8]:
# Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
#start = vacation_start[["Lat", "Lng"]].to_numpy()
# end = vacation_end[["Lat", "Lng"]].to_numpy()
# stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
# stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
# stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()
# start

start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0],vacation_stop3["Lng"].to_numpy()[0]

print(end)

(45.5234, -122.6762)

## Use the [gmaps documentation](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#directions-layer) to create a directions layer map using the variables from the previous step. Where the starting and ending city are the same city, the `waypoints` are the three other cities, and the `travel_mode` is either `"DRIVING"`, `"BICYCLING"`, or `"WALKING"`.

In [9]:
# Define a new figure object
fig = gmaps.figure()

# Create a direction layer map using the start and end latitude-longitude pairs, and stop1, stop2, and stop3 as the waypoints.
# The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
vacation_itinerary = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')

# Add the layer to the map
fig.add_layer(vacation_itinerary)
# YOUR CODE HERE


# Display the map
fig
# YOUR CODE HERE

Figure(layout=FigureLayout(height='420px'))

## Use the provided `concat()` function code snippet to combine the four separate city DataFrames into one DataFrame.

In [10]:
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat(
    [
        vacation_start,
        vacation_stop1,
        vacation_stop2,
        vacation_stop3
    ],
    ignore_index = True
)

# Display sample data
itinerary_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
0,Portland,US,45.5234,-122.6762,78.84,54,20,6.91,smoke,Embassy Suites by Hilton Portland Downtown
1,San Jose,US,37.3394,-121.8950,73.22,69,0,8.05,clear sky,The Westin San Jose
2,Morro Bay,US,35.3658,-120.8499,76.93,92,37,1.99,scattered clouds,Inn at Morro Bay
3,Saint George,US,37.1041,-113.5841,82.99,25,0,1.01,clear sky,Best Western Plus Abbey Inn

## Refactor the code from Step 6 to create a new marker layer map of the cities on the travel route.

In [11]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [12]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Define a new figure object
fig = gmaps.figure()

# Add the layer to the map
fig.add_layer(marker_layer)
# YOUR CODE HERE

# Display the map
fig
# YOUR CODE HERE

Figure(layout=FigureLayout(height='420px'))